---
# TODO: Build better testing for multiple containers and os support
language: python
python: "2.7"

sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible
  - pip install ansible-lint

  # Check ansible version
  - ansible --version

  # Link github repo to ansible-galaxy name
  - ln -s  $PWD ../while-true-do.yum

# Run the tests
script:
  - chmod +x tests/test-ansible.sh
  - tests/test-ansible.sh
  - chmod +x tests/test-spelling.sh
  - tests/test-spelling.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
