---
- name: Install yum packages
  package:
    name: "{{ wtd_yum_packages }}"
    state: present
  tags:
    - yum
    - package-manager

- name: Configure yum
  template:
    src: yum.conf.j2
    dest: /etc/yum.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - yum
    - config
